name = "weather-backend"
main = "src/index.ts"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

# Workers Analytics Engine - none configured

# KV namespaces for weather data caching
[[kv_namespaces]]
binding = "WEATHER_CACHE"
id = "c041bceafa0146e0a2c58629ef7e0852"
preview_id = "fc2023f1e990446ebdf656f2a892ec5e"

# Cron triggers for weather data collection
[triggers]
crons = [
  # Brambles Bank - every 5 minutes (more frequent for comprehensive data)
  "*/5 * * * *",
  # Seaview - every 2 minutes (real-time wind data)  
  "*/2 * * * *",
  # Lymington - every 3 minutes (stable data source)
  "*/3 * * * *"
]

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# API keys and sensitive data go here, not in this file

# Development configuration
[env.development]
[[env.development.kv_namespaces]]
binding = "WEATHER_CACHE"
id = "8388f5851c3e47b49b3a6596b94c7a9a"

[env.development.vars]
ENVIRONMENT = "development"
