name = "weather-backend"
main = "src/index.ts"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

# Workers Analytics Engine - none configured

# KV namespaces for weather data caching
[[kv_namespaces]]
binding = "WEATHER_CACHE"
id = "c041bceafa0146e0a2c58629ef7e0852"
preview_id = "fc2023f1e990446ebdf656f2a892ec5e"

# Cron triggers for weather data collection
[triggers]
crons = [
  # Chamonix stations - every 3 minutes (minimum interval for device sync)
  "*/3 * * * *",
  # Solent stations - every 2 minutes (real-time marine wind data)
  "*/2 * * * *",
  # Backup comprehensive collection - every 5 minutes
  "*/5 * * * *"
]

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# API keys and sensitive data go here, not in this file

# Development configuration
[env.development]
[[env.development.kv_namespaces]]
binding = "WEATHER_CACHE"
id = "8388f5851c3e47b49b3a6596b94c7a9a"

[env.development.vars]
ENVIRONMENT = "development"
